name: Main Branch Workflow

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 */7 * *" # 每7天在UTC时间0点运行

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      pages: write
      id-token: write

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整历史以进行分支操作

      # 设置 Git 用户
      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      # 合并 update 分支到 main
      - name: Merge update to main
        run: |
          git checkout main
          git pull origin main
          git merge origin/update --no-edit
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 设置 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 安装依赖
      - name: Install Dependencies
        run: npm install

      # 运行 main.js
      - name: Run main.js
        run: node main.js

      # 提交生成的新文件到 main
      - name: Commit generated files
        run: |
          git add .
          git commit -m "last updated at $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 部署到 GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
