name: Update Branch Workflow

on:
  push:
    branches:
      - update

jobs:
  update-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout update branch
        uses: actions/checkout@v4
        with:
          ref: update

      - name: Sync with main (to avoid conflicts)
        run: |
          git fetch origin
          git checkout update
          git pull origin main --rebase
          git push origin update
        continue-on-error: true # 如果rebase冲突，继续但日志警告

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run main.js to update MD to HTML and index.html
        run: node main.js # 在根目录执行，更新根目录的index.html

      - name: Commit changes if any
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update MD to HTML and index.html at $(date +'%Y-%m-%d %H:%M:%S')"
            git push origin update
          fi

      - name: Create Pull Request to main
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto-update from update branch"
          title: "Auto PR: Updates from update branch"
          body: "Automated PR with latest updates from update branch."
          branch: update
          base: main
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          delete-branch: false

      - name: Enable Auto-Merge on PR
        if: ${{ steps.cpr.outputs.pull-request-number }}
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
